#spring.jpa.hibernate.ddl-auto=none
server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    
    
spring:
  datasource:
    url: jdbc:mysql://192.168.1.16:3306/db_springboot_backend
    username: myuser
    password: myuser2649
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
