server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_springboot_backend?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: myuser
    password: myuser2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: ms-cliente-example
