#spring.jpa.hibernate.ddl-auto=none
spring:
  datasource:
    url: jdbc:mysql://192.168.1.16:3306/db_springboot_backend?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: myuser
    password: myuser2649
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8082